package com.etf.volume.simulator.service.entity;
// default package
// Generated Jul 24, 2016 3:20:21 PM by Hibernate Tools 5.0.0.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToOne;
import javax.persistence.PrimaryKeyJoinColumn;
import javax.persistence.Table;
import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.Parameter;

/**
 * Price generated by hbm2java
 */
@Entity
@Table(name = "price", catalog = "stocks")
public class Price implements java.io.Serializable {

	private static final long serialVersionUID = 7034812686414924241L;
	
	private int pullDateId;
	private PullDate pullDate;
	private Integer previousDayClosingPrice;
	private Integer openPrice;
	private Integer currentPrice;

	public Price() {
	}

	public Price(PullDate pullDate) {
		this.pullDate = pullDate;
	}

	public Price(PullDate pullDate, Integer previousDayClosingPrice, Integer openPrice, Integer currentPrice) {
		this.pullDate = pullDate;
		this.previousDayClosingPrice = previousDayClosingPrice;
		this.openPrice = openPrice;
		this.currentPrice = currentPrice;
	}

	@GenericGenerator(name = "generator", strategy = "foreign", parameters = @Parameter(name = "property", value = "pullDate"))
	@Id
	@GeneratedValue(generator = "generator")

	@Column(name = "pullDateId", unique = true, nullable = false)
	public int getPullDateId() {
		return this.pullDateId;
	}

	public void setPullDateId(int pullDateId) {
		this.pullDateId = pullDateId;
	}

	@OneToOne(fetch = FetchType.LAZY)
	@PrimaryKeyJoinColumn
	public PullDate getPullDate() {
		return this.pullDate;
	}

	public void setPullDate(PullDate pullDate) {
		this.pullDate = pullDate;
	}

	@Column(name = "previousDayClosingPrice")
	public Integer getPreviousDayClosingPrice() {
		return this.previousDayClosingPrice;
	}

	public void setPreviousDayClosingPrice(Integer previousDayClosingPrice) {
		this.previousDayClosingPrice = previousDayClosingPrice;
	}

	@Column(name = "openPrice")
	public Integer getOpenPrice() {
		return this.openPrice;
	}

	public void setOpenPrice(Integer openPrice) {
		this.openPrice = openPrice;
	}

	@Column(name = "currentPrice")
	public Integer getCurrentPrice() {
		return this.currentPrice;
	}

	public void setCurrentPrice(Integer currentPrice) {
		this.currentPrice = currentPrice;
	}

}
