package com.etf.volume.simulator.service.entity;
// default package
// Generated Jul 24, 2016 3:20:21 PM by Hibernate Tools 5.0.0.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * PullDate generated by hbm2java
 */
@Entity
@Table(name = "pull_date", catalog = "stocks")
public class PullDate implements java.io.Serializable {

	private static final long serialVersionUID = -947954625307913793L;
	
	private Integer pullDateId;
	private Ticker ticker;
	private Date pullDate;
	private Price price;
	private Volume volume;

	public PullDate() {
	}

	public PullDate(Ticker ticker, Date pullDate) {
		this.ticker = ticker;
		this.pullDate = pullDate;
	}

	public PullDate(Ticker ticker, Date pullDate, Price price, Volume volume) {
		this.ticker = ticker;
		this.pullDate = pullDate;
		this.price = price;
		this.volume = volume;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "pullDateId", unique = true, nullable = false)
	public Integer getPullDateId() {
		return this.pullDateId;
	}

	public void setPullDateId(Integer pullDateId) {
		this.pullDateId = pullDateId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "tickerId", nullable = false)
	public Ticker getTicker() {
		return this.ticker;
	}

	public void setTicker(Ticker ticker) {
		this.ticker = ticker;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "pullDate", nullable = false, length = 19)
	public Date getPullDate() {
		return this.pullDate;
	}

	public void setPullDate(Date pullDate) {
		this.pullDate = pullDate;
	}

	@OneToOne(fetch = FetchType.LAZY, mappedBy = "pullDate")
	public Price getPrice() {
		return this.price;
	}

	public void setPrice(Price price) {
		this.price = price;
	}

	@OneToOne(fetch = FetchType.LAZY, mappedBy = "pullDate")
	public Volume getVolume() {
		return this.volume;
	}

	public void setVolume(Volume volume) {
		this.volume = volume;
	}

}
