package com.etf.volume.simulator.service.entity;
// default package
// Generated Jul 24, 2016 3:20:21 PM by Hibernate Tools 5.0.0.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Ticker generated by hbm2java
 */
@Entity
@Table(name = "ticker", catalog = "stocks", uniqueConstraints = @UniqueConstraint(columnNames = "ticker"))
public class Ticker implements java.io.Serializable {

	private static final long serialVersionUID = 588287417052448479L;
	
	private Integer tickerId;
	private String ticker;
	private String companyName;
	private Set<PullDate> pullDates = new HashSet<PullDate>(0);

	public Ticker() {
	}

	public Ticker(String ticker) {
		this.ticker = ticker;
	}

	public Ticker(String ticker, String companyName, Set<PullDate> pullDates) {
		this.ticker = ticker;
		this.companyName = companyName;
		this.pullDates = pullDates;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "tickerId", unique = true, nullable = false)
	public Integer getTickerId() {
		return this.tickerId;
	}

	public void setTickerId(Integer tickerId) {
		this.tickerId = tickerId;
	}

	@Column(name = "ticker", unique = true, nullable = false, length = 10)
	public String getTicker() {
		return this.ticker;
	}

	public void setTicker(String ticker) {
		this.ticker = ticker;
	}

	@Column(name = "companyName", length = 45)
	public String getCompanyName() {
		return this.companyName;
	}

	public void setCompanyName(String companyName) {
		this.companyName = companyName;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "ticker")
	public Set<PullDate> getPullDates() {
		return this.pullDates;
	}

	public void setPullDates(Set<PullDate> pullDates) {
		this.pullDates = pullDates;
	}

}
