package com.stock.technicals.service.entity;
// default package
// Generated Jul 24, 2016 3:20:21 PM by Hibernate Tools 5.0.0.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToOne;
import javax.persistence.PrimaryKeyJoinColumn;
import javax.persistence.Table;
import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.Parameter;

/**
 * Volume generated by hbm2java
 */
@Entity
@Table(name = "volume", catalog = "stocks")
public class Volume implements java.io.Serializable {

	private static final long serialVersionUID = -3820785318458737375L;
	
	private int pullDateId;
	private PullDate pullDate;
	private Integer currentVolume;
	private Integer averageVolume;

	public Volume() {
	}

	public Volume(PullDate pullDate) {
		this.pullDate = pullDate;
	}

	public Volume(PullDate pullDate, Integer currentVolume, Integer averageVolume) {
		this.pullDate = pullDate;
		this.currentVolume = currentVolume;
		this.averageVolume = averageVolume;
	}

	@GenericGenerator(name = "generator", strategy = "foreign", parameters = @Parameter(name = "property", value = "pullDate"))
	@Id
	@GeneratedValue(generator = "generator")

	@Column(name = "pullDateId", unique = true, nullable = false)
	public int getPullDateId() {
		return this.pullDateId;
	}

	public void setPullDateId(int pullDateId) {
		this.pullDateId = pullDateId;
	}

	@OneToOne(fetch = FetchType.LAZY)
	@PrimaryKeyJoinColumn
	public PullDate getPullDate() {
		return this.pullDate;
	}

	public void setPullDate(PullDate pullDate) {
		this.pullDate = pullDate;
	}

	@Column(name = "currentVolume")
	public Integer getCurrentVolume() {
		return this.currentVolume;
	}

	public void setCurrentVolume(Integer currentVolume) {
		this.currentVolume = currentVolume;
	}

	@Column(name = "averageVolume")
	public Integer getAverageVolume() {
		return this.averageVolume;
	}

	public void setAverageVolume(Integer averageVolume) {
		this.averageVolume = averageVolume;
	}

}
